- hosts: webservers
  become: true
  tasks:
    - yum:
       name: "{{ item }}"
       state: present
      with_items:
          - 'mlocate.x86_64'
          - 'strace.x86_64'
          - 'java-1.8.0-openjdk.x86_64'
          - 'php.x86_64'

    - file:
       path: /home/ec2-user/{{ item }}
       state: directory
       mode: 0755
      with_items:
          - yelp
          - google
          - apple
          - yahoo
          - allstate
